"""Reading the game's own soundbanks: a sound name to decoded PCM samples.

The window has to preview what the map will actually play, and what the map
plays is the game's own samples. Nothing here ships them -- they belong to the
user's install and stay there -- so this reads them in place.

The chain is four lookups and one decoder:

    name --FNV-1 32--> event id --HIRC--> source id --DIDX/AKPK--> .wem
         --> RIFF fmt 0x0002 (Wwise IMA ADPCM) --> PCM16

Standard library only, and nothing internal. That is deliberate rather than
incidental: this module is about a file format and not about snapmap-midi, so
keeping it importable on its own is what makes promoting it out a directory
move instead of an untangling. It is also why there is no Oodle, no Vorbis, no
Opus and no native library anywhere below -- every embedded medium in these
banks is IMA ADPCM, and adding a dependency to decode formats that are not
present would buy nothing and cost the promotion.

Every constant here was measured against a retail install: 890 of 890 palette
sounds decode, durations agree with the bank metadata, and piano notes land on
equal temperament. That matters because the plausible mistakes in this format
do not raise. They produce audio that is a little too long, or clicks once per
frame, or is a tritone off -- and still plays. The four that bite are called
out at the code they would break.
"""

from __future__ import annotations

import glob
import io
import os
import struct
import wave

#: Where an install keeps its soundbanks, relative to the install root.
SOUND_SUBDIR = os.path.join("base", "sound", "soundbanks", "pc")

#: The bank generator version every offset below was measured against. All 22
#: banks in the retail install carry it.
BANK_VERSION = 113

#: One ADPCM frame, per channel: a 4-byte header then 32 bytes of nibbles.
FRAME_BYTES = 0x24

#: Samples one frame yields. 64, not 65 -- see `decode_wwise_ima`.
SAMPLES_PER_FRAME = 64

#: The only `fmt` tag these banks use. Wwise writes its own IMA variant under
#: the number the RIFF registry gave to Microsoft ADPCM's neighbour, and the
#: two are not interchangeable: see `decode_wwise_ima`.
WWISE_IMA_FORMAT_TAG = 0x0002


class SoundsUnavailableError(RuntimeError):
    """Raised when there are no soundbanks to read at all.

    Means the install path is wrong, or points at something that is not a game
    install. Typed rather than a bare OSError because the window treats it as
    an ordinary state -- "no audio yet, here is how to get some" -- and not as
    a failure to report.
    """


class UnsupportedBankVersionError(ValueError):
    """Raised when a bank was generated by a Wwise version this has not seen.

    Loud on purpose. Every chunk offset, every payload layout and the sample
    count per frame are version-specific, and a later generator moved several
    of them. Reading a version 128 bank with these offsets would not fail --
    it would resolve plausible-looking rubbish and decode it into noise, which
    is far harder to diagnose than a refusal naming the version.
    """


# ---------------------------------------------------------------- name hashing


def fnv1_32(name: str) -> int:
    """The Wwise object id for a name: FNV-1 32-bit over the lowercased name.

    FNV-**1**, not FNV-1a. The two differ only in the order of the multiply and
    the xor, they produce the same value for the empty string, and both look
    equally correct written down. Getting it backwards resolves nothing at all,
    which at least fails honestly -- but it is the first thing to check when a
    name that plainly exists cannot be found.

    Anchored by `fnv1_32("play_pianoc4") == 260642272`.
    """
    digest = 2166136261
    for byte in name.lower().encode("utf-8"):
        digest = ((digest * 16777619) & 0xFFFFFFFF) ^ byte
    return digest


# ------------------------------------------------------------------ containers


def parse_bnk(path) -> tuple:
    """A `.bnk` to (hirc objects, embedded media index).

    Returns `({object_id: (type, payload)}, {media_id: (absolute_offset, size)})`.
    The media offsets are made absolute against the DATA chunk here, so a
    caller never has to remember which of the two they are holding -- the
    relative form and the absolute form are both plain integers and mixing
    them reads a wrong region of a multi-hundred-megabyte file without error.

    A payload runs from the object id inclusive, because that is how the size
    field in front of it counts.
    """
    objects: dict = {}
    media: dict = {}
    data_offset = None
    hirc = None
    with open(path, "rb") as handle:
        while True:
            header = handle.read(8)
            if len(header) < 8:
                break
            tag, size = struct.unpack("<4sI", header)
            position = handle.tell()
            tag = tag.decode("ascii", "replace")
            if tag == "BKHD":
                _check_bank_version(path, handle.read(4))
            elif tag == "DIDX":
                block = handle.read(size)
                for i in range(size // 12):
                    media_id, offset, length = struct.unpack("<III", block[i * 12 : i * 12 + 12])
                    media[media_id] = (offset, length)
            elif tag == "DATA":
                data_offset = position
            elif tag == "HIRC":
                hirc = handle.read(size)
            handle.seek(position + size)
    if data_offset is not None:
        media = {m: (data_offset + o, s) for m, (o, s) in media.items()}
    if hirc:
        objects = _parse_hirc(hirc)
    return objects, media


def _check_bank_version(path, field: bytes) -> None:
    """Refuse a bank whose generator version is not the measured one."""
    if len(field) < 4:
        raise UnsupportedBankVersionError("%s: BKHD chunk is truncated" % path)
    version = struct.unpack("<I", field)[0]
    if version != BANK_VERSION:
        raise UnsupportedBankVersionError(
            "%s: soundbank version %d, expected %d -- every offset in this reader is "
            "version-specific and would silently misread" % (path, version, BANK_VERSION)
        )


def _parse_hirc(hirc: bytes) -> dict:
    """The HIRC chunk to {object id: (type, payload)}.

    Each record is a type byte, a u32 size, and then `size` bytes STARTING at
    the object id. The id is therefore inside the payload and not in front of
    it, which is why every offset in `resolve_sources` is four higher than the
    field lists in the format notes suggest.
    """
    objects = {}
    count = struct.unpack("<I", hirc[:4])[0]
    cursor = 4
    for _ in range(count):
        kind = hirc[cursor]
        size = struct.unpack("<I", hirc[cursor + 1 : cursor + 5])[0]
        object_id = struct.unpack("<I", hirc[cursor + 5 : cursor + 9])[0]
        objects[object_id] = (kind, hirc[cursor + 5 : cursor + 5 + size])
        cursor += 5 + size
    return objects


def parse_akpk(path) -> dict:
    """A `.pck` to {media_id: (path, absolute_offset, size)}.

    The stream table's offsets are stored scaled by a per-entry block size, so
    a raw `start` is a block index and not a byte position. An unscaled read
    lands within the first few megabytes of a two-gigabyte file and returns
    something that is not RIFF, which at least fails -- but only by luck.

    Returns {} rather than raising for a file that is not an AKPK, so a caller
    can point this at every `.pck` in a folder without pre-screening them.
    """
    with open(path, "rb") as handle:
        head = handle.read(8)
        if head[:4] != b"AKPK":
            return {}
        header_size = struct.unpack("<I", head[4:8])[0]
        handle.seek(0)
        buffer = handle.read(8 + header_size)
    cursor = 8
    _version, language_size, bank_size, _stream_size, _extern_size = struct.unpack(
        "<IIIII", buffer[cursor : cursor + 20]
    )
    cursor += 20
    cursor += language_size  # the language map: nothing here is localised
    cursor += bank_size  # the soundbank table: banks are read directly instead
    entries = {}
    count = struct.unpack("<I", buffer[cursor : cursor + 4])[0]
    for i in range(count):
        base = cursor + 4 + i * 20
        media_id, block, size, start, _language = struct.unpack("<IIIII", buffer[base : base + 20])
        entries[media_id] = (path, start * block if block else start, size)
    return entries


# ------------------------------------------------------------- HIRC resolution

_TYPE_SOUND = 2
_TYPE_EVENT_ACTION = 3
_TYPE_EVENT = 4

#: Object types that hold children rather than a source of their own: the
#: random, sequence, switch, blend and actor-mixer containers.
_CONTAINERS = frozenset({5, 6, 7, 9, 10, 11, 12, 13})

#: How deep a container chain may nest before this gives up. Containers can
#: legally hold containers, and a malformed bank can hold a cycle; `seen`
#: catches the cycle and this catches the rest.
_MAX_DEPTH = 12


def _children(payload: bytes, valid) -> list:
    """A container's child list, found by shape rather than by offset.

    Container payloads carry a variable-length property block in front of the
    child list, so the list does not sit at a fixed offset and cannot be
    reached by counting. What is searched for instead is a u32 count followed
    by exactly that many ids that all name real objects in this bank -- a
    pattern a run of arbitrary bytes does not accidentally satisfy. The longest
    such run wins, because a short false positive is possible where a long one
    is not.
    """
    best = None
    for offset in range(4, len(payload) - 4):
        count = struct.unpack("<I", payload[offset : offset + 4])[0]
        if not (1 <= count <= 2000) or offset + 4 + count * 4 > len(payload):
            continue
        ids = struct.unpack("<%dI" % count, payload[offset + 4 : offset + 4 + count * 4])
        if all(i in valid for i in ids) and (best is None or count > best[0]):
            best = (count, ids)
    return list(best[1]) if best else []


def resolve_sources(objects, object_id: int, depth: int = 0, seen=None) -> list:
    """An object id to [(source media id, stream type), ...].

    An event names actions, an action names a target, and the target is either
    a sound or a container of them. Following that chain is the whole reason
    the HIRC is parsed at all: a sound name resolves to an event, and events
    hold no media.

    `seen` is not an optimisation. A switch container may name a sibling that
    names it back, and without it this recurses until the stack goes.
    """
    seen = seen if seen is not None else set()
    if object_id in seen or depth > _MAX_DEPTH or object_id not in objects:
        return []
    seen.add(object_id)
    kind, payload = objects[object_id]
    found: list = []
    if kind == _TYPE_EVENT:
        count = struct.unpack("<I", payload[4:8])[0]
        if 0 < count < 500 and 8 + count * 4 <= len(payload):
            for action in struct.unpack("<%dI" % count, payload[8 : 8 + count * 4]):
                found += resolve_sources(objects, action, depth + 1, seen)
    elif kind == _TYPE_EVENT_ACTION:
        found += resolve_sources(objects, struct.unpack("<I", payload[6:10])[0], depth + 1, seen)
    elif kind == _TYPE_SOUND:
        found.append((struct.unpack("<I", payload[9:13])[0], payload[8]))
    elif kind in _CONTAINERS:
        for child in _children(payload, objects):
            found += resolve_sources(objects, child, depth + 1, seen)
    return found


# ------------------------------------------------------------ Wwise IMA ADPCM

# The IMA step ladder and index table, unchanged since the original spec.
_STEP = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230,
    253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963,
    1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024,
    3327, 3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493,
    10442, 11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086,
    29794, 32767,
]  # fmt: skip
_INDEX = [-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8]
_MAX_STEP_INDEX = len(_STEP) - 1


def decode_wwise_ima(data: bytes, channels: int, block_align: int) -> list:
    """Wwise IMA ADPCM to [[channel 0 samples], [channel 1 samples], ...].

    Four things here are wrong in every implementation that was reached for
    first, and not one of them raises. Each produces audio that plays.

    **A frame is 64 samples, not 65.** The 4-byte header holds a predictor that
    is emitted as sample 0, then only 63 of the 64 nibbles are consumed and the
    last is padding. Decoding all 64 gives 65 samples per frame: 1.56% long, a
    click at every frame boundary, and a pitch that drifts flat against the
    written sample rate. It sounds like a bad rip rather than like a bug.

    **The delta is the MUL form**, `((code & 7) * 2 + 1) * step >> 3`. The ADD
    form that the reference decoder and the standard library's `audioop` use --
    accumulating `step >> 3` plus conditional halves -- differs by a fraction of
    a step per sample. That integrates into audible roughness on sustained
    tones and nothing at all on short percussion, so it passes a spot check.

    **The low nibble comes first.** Reversed, the waveform is still a waveform;
    it is simply the wrong one, at roughly the right envelope.

    **Multichannel clusters whole frames**, `[ch0 36B][ch1 36B][ch0 36B]...`,
    not MS-IMA's 4-byte word interleave. Read as words, a stereo file decodes
    into two channels of alternating garbage that still has the right length
    and duration.

    `audioop` is not an option regardless: it was removed in Python 3.13, and
    it reads the high nibble first and uses the ADD form, so it is wrong on two
    of the four counts anyway.
    """
    if block_align != FRAME_BYTES * channels:
        raise ValueError(
            "unexpected blockAlign %d for %d channel(s); this decoder assumes %d bytes "
            "per channel per frame" % (block_align, channels, FRAME_BYTES)
        )
    out = [[] for _ in range(channels)]
    for index in range(len(data) // block_align):
        block = data[index * block_align : (index + 1) * block_align]
        for channel in range(channels):
            frame = block[channel * FRAME_BYTES : (channel + 1) * FRAME_BYTES]
            predictor, step_index = struct.unpack("<hB", frame[0:3])
            step_index = _clamp_index(step_index)
            samples = out[channel]
            samples.append(predictor)
            body = frame[4:]
            for i in range(SAMPLES_PER_FRAME - 1):  # the 64th nibble is padding
                byte = body[i >> 1]
                code = (byte >> 4) & 0xF if (i & 1) else byte & 0xF
                step = _STEP[step_index]
                delta = ((code & 7) * 2 + 1) * step >> 3
                predictor = predictor - delta if code & 8 else predictor + delta
                if predictor < -32768:
                    predictor = -32768
                elif predictor > 32767:
                    predictor = 32767
                step_index = _clamp_index(step_index + _INDEX[code])
                samples.append(predictor)
    return out


def _clamp_index(value: int) -> int:
    """Hold the step index inside the ladder.

    Clamped rather than wrapped or trusted: the index walks by up to 8 per
    sample and a header may carry any byte at all, so an unclamped read runs
    off the end of `_STEP` on ordinary content, not on corrupt content.
    """
    if value < 0:
        return 0
    return _MAX_STEP_INDEX if value > _MAX_STEP_INDEX else value


# ------------------------------------------------------------------- top level


class DoomSounds:
    """Every sound in one install, addressable by name.

    Built once and reused. The constructor walks the retail chunk tables under
    `base/sound/soundbanks/pc` and seeks straight past their audio. It never
    recursively discovers mod banks elsewhere in the install: runtime-injected
    sounds need an explicit catalog and precedence contract before they can
    safely join the stock SnapMap palette.
    """

    def __init__(self, install_dir):
        base = os.path.join(os.fspath(install_dir), SOUND_SUBDIR)
        if not os.path.isdir(base):
            raise SoundsUnavailableError(
                "no soundbanks under %s -- this does not look like a game install" % base
            )
        self.install_dir = install_dir
        self.objects: dict = {}
        self.media: dict = {}
        for path in sorted(glob.glob(os.path.join(base, "*.bnk"))):
            objects, media = parse_bnk(path)
            self.objects.update(objects)
            for media_id, (offset, size) in media.items():
                self.media.setdefault(media_id, (path, offset, size))
        self.stream: dict = {}
        for path in sorted(glob.glob(os.path.join(base, "*.pck"))) + sorted(
            glob.glob(os.path.join(base, "*", "*.pck"))
        ):
            self.stream.update(parse_akpk(path))

    def _locate(self, media_id: int):
        """(path, offset, size) for a media id, or None when it is in neither.

        The `.pck` copy wins over the bank copy whenever both exist, and that
        ordering is load-bearing. A media id present in both is a **prefetch
        stub** in the bank: the first fraction of a second, kept inline so the
        engine can start playing while the stream seeks. It is a valid RIFF
        with a valid header and it decodes cleanly -- into a sound that stops
        after a few frames. Nothing about it announces that it is a fragment.
        """
        return self.stream.get(media_id) or self.media.get(media_id)

    def _media_location(self, name: str):
        """Where a name's audio lives, by the same first-source rule `pcm` uses."""
        sources = resolve_sources(self.objects, fnv1_32(name))
        return self._locate(sources[0][0]) if sources else None

    def names(self, candidates) -> set:
        """Which of `candidates` this install can actually produce audio for.

        Takes the candidates rather than enumerating them, because a bank
        stores hashes and not names. `fnv1_32` is one-way, so there is no set
        of names in here to hand back -- the only way to learn that a name
        exists is to hash it and look. A caller that wants "everything" passes
        the sound palette, which is the list this product cares about anyway.

        Checked by the same first-source rule `pcm` uses, so a name in this set
        is a name `pcm` will not raise on.
        """
        return {name for name in candidates if self._media_location(name) is not None}

    def pcm(self, name: str) -> tuple:
        """A sound name to (channels, sample rate, per-channel samples).

        Raises KeyError naming the sound for both ways this can fail -- the
        name resolves to no event, or the event's media is not in this install
        (a DLC sound in a base-game install reaches the second). Both are
        "this install cannot play that", which is a caller's problem to route
        around rather than an error in the reading.
        """
        sources = resolve_sources(self.objects, fnv1_32(name))
        if not sources:
            raise KeyError("%s: no such Wwise event in these soundbanks" % name)
        location = self._locate(sources[0][0])
        wem = _read_slice(location) if location else None
        if not wem or wem[:4] != b"RIFF":
            raise KeyError("%s: the media it names is not present in this install" % name)
        fmt, data = _riff_chunks(wem)
        if fmt is None or data is None:
            raise KeyError("%s: its media has no fmt or no data chunk" % name)
        tag, channels, rate, _bytes_per_second, align, _bits = struct.unpack("<HHIIHH", fmt[:16])
        if tag != WWISE_IMA_FORMAT_TAG:
            raise NotImplementedError(
                "%s: format tag 0x%04x, and only 0x%04x (Wwise IMA ADPCM) is decoded here"
                % (name, tag, WWISE_IMA_FORMAT_TAG)
            )
        return channels, rate, decode_wwise_ima(data, channels, align)

    def wav_bytes(self, name: str) -> bytes:
        """The sound as a complete little-endian PCM16 `.wav`, in memory.

        Bytes rather than a written file because the two callers want
        different things -- one writes a cache entry, the other hands the bytes
        to a page -- and a decoder that insists on a filesystem forces the
        second one to invent a temporary file it then has to clean up.
        """
        channels, rate, per_channel = self.pcm(name)
        if channels == 1:
            flat = per_channel[0]
        else:
            flat = [per_channel[c][i] for i in range(len(per_channel[0])) for c in range(channels)]
        buffer = io.BytesIO()
        with wave.open(buffer, "wb") as writer:
            writer.setnchannels(channels)
            writer.setsampwidth(2)
            writer.setframerate(rate)
            writer.writeframes(struct.pack("<%dh" % len(flat), *flat))
        return buffer.getvalue()


def _read_slice(location) -> bytes:
    """The bytes a (path, offset, size) triple names."""
    path, offset, size = location
    with open(path, "rb") as handle:
        handle.seek(offset)
        return handle.read(size)


def _riff_chunks(wem: bytes) -> tuple:
    """The `fmt ` and `data` payloads of a RIFF, or None for either that is absent."""
    cursor, fmt, data = 12, None, None
    while cursor + 8 <= len(wem):
        tag, size = struct.unpack("<4sI", wem[cursor : cursor + 8])
        tag = tag.decode("ascii", "replace")
        if tag == "fmt ":
            fmt = wem[cursor + 8 : cursor + 8 + size]
        elif tag == "data":
            data = wem[cursor + 8 : cursor + 8 + size]
            break
        cursor += 8 + size
    return fmt, data
