"""Regenerate the shipped sound palette from a speaker declaration.

Maintainer script. It is NOT part of the installed package and nothing at
runtime calls it — the product ships the JSON this produces.

    python tools/build_sound_palette.py <speaker.decl> [-o src/snapmap_midi/data/sound_palette.json]

What is shipped and why. The declaration itself is game content and is never
committed. What comes out of it here is the list of sound NAMES, grouped by
category, in declaration order — identifiers, not audio, and the same kind of
data the General MIDI drum table has always carried inline. Shipping them is
what lets a fresh install compile a song without anyone extracting anything.

Order is preserved because the audition command plays a category in
declaration order and prints an index against each entry; re-sorting would
silently renumber every legend anyone has written down.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

# sound = "<decl>"; text = "..."; desc = "..."; category = "<category>";
_ITEM = re.compile(
    r'sound\s*=\s*"([^"]+)";\s*text\s*=\s*"[^"]*";\s*desc\s*=\s*"[^"]*";\s*category\s*=\s*"([^"]+)";',
    re.S,
)

_DEFAULT_OUT = Path(__file__).resolve().parents[1] / "src" / "snapmap_midi" / "data"

_NOTE = (
    "Sound names grouped by palette category, in declaration order. Generated by "
    "tools/build_sound_palette.py from a speaker declaration; the declaration itself "
    "is game data and is not distributed. These are identifiers only."
)


def short_category(raw: str) -> str:
    """`#str_snap_3dsnd_ins_piano_title` to `ins_piano`."""
    return raw.replace("#str_snap_3dsnd_", "").replace("_title", "")


def parse(text: str) -> "OrderedDict[str, list[str]]":
    """Category to its sound names, both in declaration order."""
    grouped: OrderedDict[str, list[str]] = OrderedDict()
    for sound, raw_category in _ITEM.findall(text):
        grouped.setdefault(short_category(raw_category), []).append(sound)
    return grouped


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("decl", help="path to the speaker declaration to read")
    parser.add_argument("-o", "--out", default=str(_DEFAULT_OUT / "sound_palette.json"))
    args = parser.parse_args(argv)

    source = Path(args.decl)
    if not source.is_file():
        sys.exit("no such declaration: {}".format(source))

    grouped = parse(source.read_text(encoding="utf-8", errors="replace"))
    if not grouped:
        sys.exit("parsed no sounds from {} -- is it a speaker declaration?".format(source))

    total = sum(len(v) for v in grouped.values())
    payload = {"_note": _NOTE, "categories": grouped}
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    # newline="" so the same declaration produces the same bytes on every
    # platform. Text mode translates to os.linesep, so a regeneration on
    # Windows would rewrite all 943 lines with CRLF and show the whole file as
    # changed. `.gitattributes` pins the checked-in form to LF as well; belt
    # and braces, because only one of the two protects a contributor whose
    # `core.autocrlf` is off.
    with open(out, "w", encoding="utf-8", newline="") as handle:
        handle.write(json.dumps(payload, indent=1) + "\n")

    print("{} sounds in {} categories -> {}".format(total, len(grouped), out))
    for category, sounds in sorted(grouped.items(), key=lambda kv: -len(kv[1])):
        print("  {:>4}  {}".format(len(sounds), category))
    return 0


if __name__ == "__main__":
    sys.exit(main())
